using System;
using KTableau.DAL.models;
using Microsoft.EntityFrameworkCore;
using NLog;


namespace KTableau.DAL
{
    public class KTableauDBContext : DbContext
    {   

        // All tables DBContext has to control under
        public DbSet<User> Users { get; set; }
        public DbSet<Transition> Transitions { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<Note> Notes { get; set; }


        // :base is the Java's 'super'
        public KTableauDBContext(DbContextOptions<KTableauDBContext> options) : base(options)
        {  
            
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Connection string
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=KTableau");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // UserId is the PK for the entity User (autogenerated)
            modelBuilder.Entity<User>().HasKey(p => p.UserId);
            modelBuilder.Entity<User>().Property(p => p.UserId).ValueGeneratedOnAdd();

        }
    }
}
